export const list = [
    { toll: "Rv. 110 – Seut"},
    { toll: "Rv. 110 – Fredrikstadbrua øst"},
    { toll: "Fv. 381 – Veumveien"},
    { toll: "Fv. 109 – Råbekken"},
    { toll: "Kv. – Dikeveien"},
    { toll: "Kv. – Evjebekken"},
    { toll: "Fv. 112 – Hauge bru"},
    { toll: "Fv. 109 – Rolvsøysund"},
    { toll: "Rv. 22 – Årum vest"},
    { toll: "Fv. 107 – Vardeveien"},
    { toll: "Fv. 130 – Skjærviken"},
    { toll: "Rv. 22 – Hafslund syd"},
    { toll: "Kv. Navestadveien"},
    { toll: "Fv. 118 – Sarpsbru"},
    { toll: "Fv. 114 – Grålum"},
    { toll: "E6 – Rampeavkjøring Lekevoll fra sør"},
    { toll: "E6 – Rampeavkjøring Lekevoll fra nord"},
    { toll: "Fv. 118 – Kalnes"},
    { toll: "Fv. 109 – Alvim vest"},
    { toll: "Fv. 1168 – Alvimveien"},
    { toll: "E6 – Rampeavkjøring Alvim fra nord"},
    { toll: "E6 – Rampeavkjøring Alvim fra sør"},
    { toll: "Kv. Tuneveien"},
    { toll: "Fv. – Ny bru i Fredrikstad"}
]